spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security
    username: root
    password: rootUser@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
server:
  port: 4100


---
spring:
  jpa:
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ALL
    open-in-view: false


